### ISSUE TITLE
password option in genkeys()

### ISSUE THREAD

**Issue by gadenbuie** [SurgicalInformatics/encryptr#1]
Thanks for your work on this package! I've been playing with it a bit and exploring the API and have two suggestions related to the setting of the password in `genkeys()`. 

The first is to suggest exposing the `password` argument in `genkeys()`. As currently implemented, it not possible for a user to programmatically generate keys due to the `askpass()` prompt.

https://github.com/SurgicalInformatics/encryptr/blob/4624dbce5916403742973a7ea3c449c03bf1aa6c/R/genkeys.R#L33-L37

You could easily refactor the password prompt into

```
ask_pass <- function() {
  askpass::askpass(prompt = paste(
    "Please choose a password for your private key.",
    "This password CANNOT be recovered if lost.",
    "Please store the password in a safe location.",
    sep = "\n"))
}
```

and set the default value of `password = ask_pass()`, allowing users to choose to override the behavior but keeping the default workflow.

The second suggestion is that on RStudio the prompt is quite jumbled when displayed.

<img width="404" alt="image" src="https://user-images.githubusercontent.com/5420529/53350354-e8c25d00-38ec-11e9-8274-da669ddd6f49.png">

The above refactoring also displays properly in RStudio.

<img width="401" alt="image" src="https://user-images.githubusercontent.com/5420529/53350422-0abbdf80-38ed-11e9-9191-7d9df9e63888.png">

Finally, while looking at `genkeys()` I realized that the key_name arguments aren't called in the `write_pem()` step, so all keys will be named `id_rsa` by default regardless of the input to `genkeys()`.

https://github.com/SurgicalInformatics/encryptr/blob/4624dbce5916403742973a7ea3c449c03bf1aa6c/R/genkeys.R#L22

https://github.com/SurgicalInformatics/encryptr/blob/4624dbce5916403742973a7ea3c449c03bf1aa6c/R/genkeys.R#L38-L39

If you're interested in the above I could quickly work these suggestions into a PR.

**Comment by ewenharrison** [comment]
Many thanks for this and the work in the pull request. It is greatly appreciated. 
Along with some other changes, I have incorporated your suggestions in the latest push. 
All but the option of exposing the password option. 
This was designed in this way intentionally to avoid having passwords written into scripts. This seemed to the team exactly what we were trying to avoid. 
Is there a particular situation you see in which the password must be included in the script? If there is a good argument we will include. But there are lots of good reasons not to do this. 
Many thanks again.

**Comment by gadenbuie** [comment]
Exposing `password` wouldn't be for end-users as much as other developers wanting to extend, wrap or build upon encryptr. On the other hand, because `genkeys()` is  a convenience function around a couple lines of standard `openssl` usage, re-writing `genkeys()` to have access to `password` isn't that hard or limiting.

It's also worth noting that `askpass::askpass()` returns `NULL` in a non-interactive setting, so when run inside a source script it's not at all possible to set a password. 

Despite returning `NULL` non-interactively, you can still use all but the last test I added in the PR.

**Comment by ewenharrison** [comment]
I guess I feel pretty strongly about not allowing users the option to make a mistake with a password. Together with wanting to go to information governance authorities and say we are using a system in which the password is not recorded in the script. 

An alternative (that may be over thinking it) is to have `genkeys_()` specifically for developers that allows that option, but is not included in the standard package vignettes etc. 

Thanks again for this help and discussion. I should have said above that I haven't incorporated the `tests`,  but will do with a PR when we conclude this thread.

**Comment by gadenbuie** [comment]
That makes sense. And any developer writing code around that part of the workflow should probably be using the lower level packages to have full control over the process.

**Comment by ewenharrison** [comment]
Great thank you. Ok, I’ll incorporate the tests from your pull request, unless you want to adjust it. I never know the etiquette of these things. Best wishes.

**Comment by gadenbuie** [comment]
Cool and no worries. Feel free to take what you need from the PR and just close it when you're done so I know to update my fork. Cheers!

**Comment by ewenharrison** [comment]
Changes made. Thanks again.
