### ISSUE TITLE
Consistent encryption of a clear-text

### ISSUE THREAD

**Issue by aetiologicCanada** [SurgicalInformatics/encryptr#3]
Recognizing at the outset that my request is exactly for a feature that  encryptr says it does not do (and for good reason) provide. I'll ask my question hoping that there might be another workflow.

I have a dataset that has a unique identifier, and I wish to never  know the clear text value of this identifier.  However I do need to group together records for the same identifier, so that I can follow patients through time, conduct linkages, etc.   Encryptr is very clear that given a given a fixed clear-text input, RSA will generate N cypher-texts, so clearly RSA/encryptr is not what I need.  But what do I need?

Can anyone suggest a workflow that uses encryption, but does provide a consistent output across  iterations for a fixed cleartext input?

Many thanks,

**Comment by aetiologicCanada** [comment]
and to answer my own question.
library(tidyverse)
library(encryptr)
listofids = c("A", "B", "C", "A")
ids_in_table <- tibble(ids=listofids)
ids_in_table
class(ids_in_table)
  str(ids_in_table)

lookuptable <- tibble(
  listofuniqueids = unique(ids_in_table$ids),
  encrypted = encrypt_vec(listofuniqueids)
)
lookuptable

combined <- dplyr::left_join(ids_in_table, lookuptable, by=c("ids" = "listofuniqueids"))
View(combined)

That works, but it requires me to have all my data in clear-text form at some point in time, and what I'd rather do is to convert the clear-text to cypher ASAP.  There must be a more elegant solution.

**Comment by ewenharrison** [comment]
![1 23RpkZuWAeSP7x0YdMtsdQ](https://user-images.githubusercontent.com/3391394/62195555-2a5fa400-b374-11e9-95e5-279268274458.png)

There are 3 approaches. encryptr uses asymmetric encryption for the reasons you describe. 

You could hash your IDs. This will provide an invariant "digest" which can be matched. 

The disadvantages are: 

1. It is not really encryption in the sense that the plaintext cannot be recovered/unencrypted. 
2. A key (often called "salt") needs to be used every time (compared with public key where this isn't required). 
3. The key cannot be shared or all data is compromised (compared with public key).
4. If the key is compromised, then an adversary can make lookup table using the structure of the ID - e.g. make a lookup table for every possible date of birth and then match. 
5. If the key is compromised, you need to start the process again with the plaintext.  

We haven't included the following in the package given the weaknesses above.

Interested in your thoughts. 

```
openssl::sha256(c("John", "Brian", "John"), key = "mysecretkey")
[1] "57242f27cd5ba1b142f5b9b0ccb14d2a982f963270aff97b8e706fa11ed9c34c"
[2] "b1baf9f550eecf21973c7a7805ccc66b7b754873ec5ca5ae5527f49b9697e416"
[3] "57242f27cd5ba1b142f5b9b0ccb14d2a982f963270aff97b8e706fa11ed9c34c"
```

**Comment by aetiologicCanada** [comment]
This is very helpful, and the graphic much appreciated.  

1) Decryption not always needed; just ability to group together clear-text (typically ID#s) without revealing cleartext.
2-5) These are meaningful vulnerabilities.

I provided some code that continues to use asymmetric encryption to accomplish this task - take a table of all unique IDs over all inputs, encrypt using RSA, merge back to master tables and then drop the clear-text ID. What one looses (I think) is the ability to augment the corpus of records and ID numbers) at some later time.  sha256 (or sha512) would seem to provide a "good enough" solution for my work if I can find a reasonable solution to key management.  But a more robust approach (if it exists) would solve a common problem for data stewards releasing data into the wild.

Many thanks for encryptr, which makes encryption workflow clearer.

**Comment by ewenharrison** [comment]
Are you perhaps missing some of the encryptr funtionality with your suggested script. 

This will take a data table, possibly with all the IDs you know up until now. It encrypts that column and replaces it with a unique ID - just a number starting from 1. 
It creates an object with a given name (`lookup` by default) of 2+ columns. The encrypted columns together with the unique ID. 
This is also written as a .csv at the specified path (working directory with name lookup.csv by default) for safety. The file can't be overwritten with a further run of the same code. 
```
library(dplyr)
library(encryptr)
genkeys()
data_ids = tibble(
  id = c("A", "B", "C", "A"),
  other_var = seq(1:4)
) %>% 
  encrypt(id, lookup = TRUE, lookup_name = "master_id_lookup")

data_ids
master_id_lookup
```
