### ISSUE TITLE
Typographic error in documentation

### ISSUE THREAD

**Issue by aetiologicCanada** [SurgicalInformatics/encryptr#4]
Documentation for encryptr::encrypt_file (v0.1.3) says "
`
crypt_file_name	Optional new name to give encrypted file. Must end with ".encrypter.bin".
`
but code throws error and complains:

`encrypt_file("diamonds2.fst", crypt_file_name="diamonds2.fst.encrypter.bin")`

Error in encrypt_file("diamonds2.fst", crypt_file_name = "diamonds2.fst.encrypter.bin") : 
  Encrypted file has incorrect name. 
  Should be created with encryptr::encrypt_file and end with '.encryptr.bin'

The issue appears to be the 2nd "e" in encrypter.bin  as suggested in the help file is not accepted by the function, which prefers encryptr.bin . 

Many thanks, again.

**Comment by ewenharrison** [comment]
Thank you for this. 
Yes it is correct in the current github version but hasn't yet made it to CRAN. 
Thank you for highlighting.
