### ISSUE TITLE
public key not found via URL

### ISSUE THREAD

**Issue by cainesap** [SurgicalInformatics/encryptr#5]
Hello,

I'm really grateful you've created this library! It's exactly what I need for secure data sharing.

However I'm encountering an error in running [this tutorial example](https://encrypt-r.org/#providing-a-public-key) from your vignette.

Encryption works fine if I provide a local file path to the `public_key_path` argument of `encrypt()`. But if I try the URL where I've copied my public key I get the following error:
```
Error in encrypt(., postcode, telephone) : Public key cannot be found.
```

Any pointers you can give would be much appreciated!
thanks, Andrew

**Comment by ewenharrison** [comment]
Thanks Andrew.
This is fixed in the github version.
`devtools::install_github("SurgicalInformatics/encryptr")`

**Comment by cainesap** [comment]
Fantastic, thanks for the quick response! All fine now :)
