### ISSUE TITLE
Error: Program type already present: org.kobjects.base64.Base64    While  Generating Signed APK

### ISSUE THREAD

**Issue by Shailendrawilliam** [SurgicalInformatics/encryptr#6]
java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives:	
com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives:	
com.android.tools.r8.CompilationFailedException: Compilation failed to complete	
com.android.tools.r8.utils.AbortException: Error: Program type already present: org.kobjects.base64.Base64      
![picturemessage_3kv5dxx3 wsr](https://user-images.githubusercontent.com/35254339/68385972-0a186000-0181-11ea-977c-4bbcc319471d.png)

Error  while  generating  Signed APK

**Comment by ewenharrison** [comment]
This is the github repo for the R package. I don't think that is what you are looking for?
